clc
clear all
close all

load('ref_data.mat')
load('ic.mat')
rfSelected={
'AGRE'...
'CV3Y-REP-EPS'...
'DEBT-MKT-CAP'...
'EPSDISP'...
'EREV'...
'LRE'...
'MKT-CAP-SALES'...
'PCF'...
'PCTCHG-DPS'...
'PCTCHG-EBITDA'...
'PCTCHG-EQUITY'...
'PCTCHG-NET_DEBT'...
'PCTCHG-UL-SALES'...
'PM6M'...
'RC1MEEREV'...
'RC1MEREV'...
'ROE'...
'UL-SALES'

};
i=1;
matrixICSector=ic{i};
ref_data_learning=ref_data_legend(1:end-1);
x=datetime(ref_data_learning, 'ConvertFrom', 'yyyymmdd');

 for j=1:8
   [sortedvalue, index]=sort(matrixICSector(:,j));
   xsorted=x(index);
   
    subplot(2,4,j)
    bar(x,matrixICSector(:,j))
    title(strcat(rfSelected(j),'/','ICB',num2str(i)));
    bar(x,matrixICSector(:,j))
 end

% for j=1:size(matrixICSector,2)
%     subplot(9,size(matrixICSector,2)/9,j)
    
% end
